title:       "Operating Systems 2021-1 (OS211)"
version:     "0030---05-Mar-2021"
copyright:   "2021-2021"
description: >- 
  rfm website
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Rafi Muhammad"
address:          "Jakarta"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://rafimuhammad01.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/rafimuhammad01/os211"
urlghpage:        "https://rafimuhammad01.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]
